### ISSUE TITLE
Illegal Group Reference when loading Goonstation.dme

### ISSUE THREAD

**Issue by ZeWaka** [tgstation/FastDMM#31]
Title.

Version: 0.7.3

![image](https://user-images.githubusercontent.com/4741640/42908081-bceae398-8a94-11e8-86ad-8f6b4e9a9da2.png)

**Comment by Rockdtben** [comment]
@ZeWaka Could you link me to the repo where you got the Goonstation.dme?

**Comment by ZeWaka** [comment]
@Rockdtben It's a private repo accessible to only Goonstation coders.

**Comment by Rockdtben** [comment]
@ZeWaka I'm going to have to add some more debugging code to FastDMM to figure out what is causing this error.

Whenever I have something ready I will ping you again.

**Comment by Rockdtben** [comment]
@ZeWaka Try out the latest https://github.com/tgstation/FastDMM/releases/tag/v0.7.4 released today and see if that helps.

**Comment by ZeWaka** [comment]
Getting a slightly different error.
```
java.lang.IllegalArgumentException: Illegal group reference
	at java.util.regex.Matcher.appendReplacement(Unknown Source)
	at com.github.tgstation.fastdmm.objtree.ObjectTree.completeTree(ObjectTree.java:191)
	at com.github.tgstation.fastdmm.FastDMM$3.run(FastDMM.java:626)
Exception in thread "Thread-7" java.lang.NullPointerException
	at com.github.tgstation.fastdmm.FastDMM.addToRecent(FastDMM.java:1167)
	at com.github.tgstation.fastdmm.FastDMM.access$600(FastDMM.java:56)
	at com.github.tgstation.fastdmm.FastDMM$3.run(FastDMM.java:647)
```

**Comment by ZeWaka** [comment]
Okay, tgstation.dme loads fine.
Attached is the contents of my folder.

However, when I load goonstation.dme I get the same error.
```
java.lang.IllegalArgumentException: Illegal group reference
	at java.util.regex.Matcher.appendReplacement(Unknown Source)
	at com.github.tgstation.fastdmm.objtree.ObjectTree.completeTree(ObjectTree.java:191)
	at com.github.tgstation.fastdmm.FastDMM$3.run(FastDMM.java:626)
Exception in thread "Thread-7" java.lang.NullPointerException
	at com.github.tgstation.fastdmm.FastDMM.addToRecent(FastDMM.java:1202)
	at com.github.tgstation.fastdmm.FastDMM.access$600(FastDMM.java:56)
	at com.github.tgstation.fastdmm.FastDMM$3.run(FastDMM.java:647)
```
[fastdmm.zip](https://github.com/tgstation/FastDMM/files/2284210/fastdmm.zip)

**Comment by Rockdtben** [comment]
@ZeWaka Okay. I'll ping you again when I have another release for you to test. Hopefully we will have it fixed this time.
